$(".Thick").hover(function(){
    $(".overview").attr("src","img/LukeFries.jpg");
  });
$(".Thin").hover(function(){
    $(".overview").attr("src","img/BasicFries.jpg");
  });
$(".Steak").hover(function(){
    $(".overview").attr("src","img/MegalFries.avif");
  });
